site_name: "MGT-python"
repo_url: "https://github.com/fourMs/MGT-python/"
site_url: "https://fourms.github.io/MGT-python"
site_dir: "site"
docs_dir: "docs"

theme:
  name: readthedocs
  include_sidebar: true
