name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
        with:
          - os: ${{ matrix.os }}
            python-version: ${{ matrix.python-version }}
            channel-priority: "strict"
            envfile: ".github/environment-ci.yml"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info -a
        conda list

    - name: Install musicalgestures
      shell: bash -l {0}
      run: python -m pip install musicalgestures

    - name: Run pytest
      shell: bash -l {0}
      run: pytest
