name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          python-version: ["3.8","3.9","3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Install FFmpeg and FFprobe
      uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg

    - name: Install Conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info -a
        conda list

    - name: Install musicalgestures
      shell: bash -l {0}
      run: python -m pip install musicalgestures