name: Run Test with Pytest

on: [push]

jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"] 

    steps:  
      - uses: actions/checkout@v3  

      - name: Update documentation files
        run: |
          pip install handsdown==1.1.0
          handsdown --external https://github.com/fourMs/MGT-python --branch master

      - uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Update documentation
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install FFmpeg and FFprobe
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  

      - name: Install musicalgestures
        shell: bash -l {0}
        run: python -m pip install musicalgestures

      - name: Lint with Ruff  
        run: |  
          pip install ruff  
          ruff --output-format=github  
        continue-on-error: true  

      ########## TODO ############
      # - name: Test with pytest
      #   shell: bash -l {0}
      #   run: |
      #     pip install pytest
      #     python -m pytest -v